// prefab -> English display name (matches DST wiki page/file names).
// Used for UI display AND to resolve icon files on dontstarve.wiki.gg
// (File:<name>.png). Entries validated by scripts/fetch_icons.mjs — any
// name the wiki doesn't know is reported, not silently dropped.
//
// Variants (_cooked/_dried) that are NOT real obtainable items (e.g.
// honey_cooked exists only as a cooking-tag entry) are omitted here on
// purpose: display falls back to the base name/icon.

export const INGREDIENT_NAMES = {
  // fruits
  pomegranate: 'Pomegranate',
  pomegranate_cooked: 'Sliced Pomegranate',
  dragonfruit: 'Dragon Fruit',
  dragonfruit_cooked: 'Prepared Dragon Fruit',
  cave_banana: 'Cave Banana',
  cave_banana_cooked: 'Cooked Banana',
  wormlight: 'Glow Berry',
  wormlight_lesser: 'Lesser Glow Berry',
  berries: 'Berries',
  berries_cooked: 'Roasted Berries',
  berries_juicy: 'Juicy Berries',
  berries_juicy_cooked: 'Roasted Juicy Berries',
  fig: 'Fig',
  fig_cooked: 'Cooked Fig',
  durian: 'Durian',
  durian_cooked: 'Extra Smelly Durian',
  watermelon: 'Watermelon',
  watermelon_cooked: 'Grilled Watermelon',
  ancientfruit_nightvision: 'Nightberry',
  ancientfruit_nightvision_cooked: 'Cooked Nightberry',

  // sweeteners
  honey: 'Honey',
  honeycomb: 'Honeycomb',
  royal_jelly: 'Royal Jelly',

  // veggies
  carrot: 'Carrot',
  carrot_cooked: 'Roasted Carrot',
  corn: 'Corn',
  corn_cooked: 'Popcorn',
  pumpkin: 'Pumpkin',
  pumpkin_cooked: 'Hot Pumpkin',
  eggplant: 'Eggplant',
  eggplant_cooked: 'Braised Eggplant',
  cutlichen: 'Lichen',
  asparagus: 'Asparagus',
  asparagus_cooked: 'Cooked Asparagus',
  onion: 'Onion',
  onion_cooked: 'Roasted Onion',
  garlic: 'Garlic',
  garlic_cooked: 'Roasted Garlic',
  tomato: 'Toma Root',
  tomato_cooked: 'Roasted Toma Root',
  potato: 'Potato',
  potato_cooked: 'Roasted Potato',
  pepper: 'Pepper',
  pepper_cooked: 'Roasted Pepper',
  red_cap: 'Red Cap',
  red_cap_cooked: 'Cooked Red Cap',
  green_cap: 'Green Cap',
  green_cap_cooked: 'Cooked Green Cap',
  blue_cap: 'Blue Cap',
  blue_cap_cooked: 'Cooked Blue Cap',
  moon_cap: 'Moon Shroom',
  moon_cap_cooked: 'Cooked Moon Shroom',
  kelp: 'Kelp Fronds',
  kelp_cooked: 'Cooked Kelp Fronds',
  kelp_dried: 'Dried Kelp Fronds',
  cactus_meat: 'Cactus Flesh',
  cactus_meat_cooked: 'Cooked Cactus Flesh',
  cactus_flower: 'Cactus Flower',
  rock_avocado_fruit_ripe: 'Ripe Stone Fruit',
  rock_avocado_fruit_ripe_cooked: 'Cooked Stone Fruit',
  mandrake: 'Mandrake',
  mandrake_cooked: 'Cooked Mandrake',

  // meats
  meat: 'Meat',
  meat_cooked: 'Cooked Meat',
  meat_dried: 'Jerky',
  monstermeat: 'Monster Meat',
  monstermeat_cooked: 'Cooked Monster Meat',
  monstermeat_dried: 'Monster Jerky',
  smallmeat: 'Morsel',
  smallmeat_cooked: 'Cooked Morsel',
  smallmeat_dried: 'Small Jerky',
  froglegs: 'Frog Legs',
  froglegs_cooked: 'Cooked Frog Legs',
  drumstick: 'Drumstick',
  drumstick_cooked: 'Fried Drumstick',
  batwing: 'Batilisk Wing',
  batwing_cooked: 'Cooked Batilisk Wing',
  batnose: 'Naked Nostrils',
  batnose_cooked: 'Charred Nostrils',
  // batnose_dried: no wiki item — falls back to base icon/name
  mole: 'Moleworm',
  plantmeat: 'Leafy Meat',
  plantmeat_cooked: 'Cooked Leafy Meat',
  trunk_summer: 'Koalefant Trunk',
  trunk_winter: 'Winter Koalefant Trunk',
  trunk_cooked: 'Koalefant Trunk Steak',

  // fish
  fish: 'Fish',
  fish_cooked: 'Fish Steak',
  eel: 'Eel',
  eel_cooked: 'Cooked Eel',
  pondfish: 'Freshwater Fish',
  fishmeat: 'Raw Fish',
  fishmeat_cooked: 'Cooked Fish',
  fishmeat_small: 'Fish Morsel',
  fishmeat_small_cooked: 'Cooked Fish Morsel',
  wobster_sheller_land: 'Wobster',
  barnacle: 'Barnacles',
  barnacle_cooked: 'Cooked Barnacles',

  // eggs
  egg: 'Egg',
  egg_cooked: 'Cooked Egg',
  bird_egg: 'Egg',
  bird_egg_cooked: 'Cooked Egg',
  tallbirdegg: 'Tallbird Egg',
  tallbirdegg_cooked: 'Fried Tallbird Egg',

  // dairy / fat
  butter: 'Butter',
  goatmilk: 'Electric Milk',
  milkywhites: 'Milky Whites',

  // misc
  butterflywings: 'Butterfly Wings',
  moonbutterflywings: 'Moon Moth Wings',
  twigs: 'Twigs',
  lightninggoathorn: 'Volt Goat Horn',
  ice: 'Ice',
  acorn: 'Birchnut',
  acorn_cooked: 'Roasted Birchnut',
  nightmarefuel: 'Nightmare Fuel',
  boneshard: 'Bone Shards',
  refined_dust: 'Collected Dust',
  forgetmelots: 'Forget-Me-Lots',
};

export const RECIPE_NAMES = {
  butterflymuffin: 'Butter Muffin',
  frogglebunwich: 'Froggle Bunwich',
  taffy: 'Taffy',
  pumpkincookie: 'Pumpkin Cookies',
  stuffedeggplant: 'Stuffed Eggplant',
  fishsticks: 'Fishsticks',
  honeynuggets: 'Honey Nuggets',
  honeyham: 'Honey Ham',
  dragonpie: 'Dragonpie',
  kabobs: 'Kabobs',
  mandrakesoup: 'Mandrake Soup',
  baconeggs: 'Bacon and Eggs',
  meatballs: 'Meatballs',
  bonestew: 'Meaty Stew',
  perogies: 'Pierogi',
  turkeydinner: 'Turkey Dinner',
  ratatouille: 'Ratatouille',
  jammypreserves: 'Fist Full of Jam',
  fruitmedley: 'Fruit Medley',
  fishtacos: 'Fish Tacos',
  waffles: 'Waffles',
  monsterlasagna: 'Monster Lasagna',
  powcake: 'Powdercake',
  unagi: 'Unagi',
  wetgoop: 'Wet Goop',
  flowersalad: 'Flower Salad',
  icecream: 'Ice Cream',
  watermelonicle: 'Melonsicle',
  trailmix: 'Trail Mix',
  hotchili: 'Spicy Chili',
  guacamole: 'Guacamole',
  jellybean: 'Jellybeans',
  potatotornado: 'Fancy Spiralled Tubers',
  mashedpotatoes: 'Creamy Potato Purée',
  asparagussoup: 'Asparagus Soup',
  vegstinger: 'Vegetable Stinger',
  bananapop: 'Banana Pop',
  frozenbananadaiquiri: 'Frozen Banana Daiquiri',
  bananajuice: 'Banana Shake',
  ceviche: 'Ceviche',
  salsa: 'Salsa Fresca',
  pepperpopper: 'Stuffed Pepper Poppers',
  californiaroll: 'California Roll',
  seafoodgumbo: 'Seafood Gumbo',
  surfnturf: "Surf 'n' Turf",
  lobsterbisque: 'Wobster Bisque',
  lobsterdinner: 'Wobster Dinner',
  barnaclepita: 'Barnacle Pita',
  barnaclesushi: 'Barnacle Nigiri',
  barnaclinguine: 'Barnacle Linguine',
  barnaclestuffedfishhead: 'Stuffed Fish Heads',
  leafloaf: 'Leafy Meatloaf',
  leafymeatburger: 'Veggie Burger',
  leafymeatsouffle: 'Jelly Salad',
  meatysalad: 'Beefy Greens',
  shroomcake: 'Mushy Cake',
  sweettea: 'Soothing Tea',
  koalefig_trunk: 'Fig-Stuffed Trunk',
  figatoni: 'Figatoni',
  figkabab: 'Figkabab',
  frognewton: 'Figgy Frogwich',
  bunnystew: 'Bunny Stew',
  justeggs: 'Plain Omelette',
  veggieomlet: 'Breakfast Skillet',
  talleggs: 'Tall Scotch Eggs',
  beefalofeed: 'Steamed Twigs',
  beefalotreat: 'Beefalo Treats',
  shroombait: 'Stuffed Night Cap',
  batnosehat: 'Milkmade Hat',
  dustmeringue: 'Amberosia',
};
